config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?  
  root  to:"users#new"
  get '/post/favorites/list', to: 'feeds#favorites_list' ,as: 'post_favorites_list'
  resources :sessions
  resources :users
  resources :feeds do
    collection do
      post :confirm
    end
  end
  get '/user/favorites/:id', to: 'feeds#make_it_as_my_favorite',as: 'post_favorite'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :content,  presence: true, length: { minimum: 4 }
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image , ImageUploader
    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, presence: true,uniqueness: true ,length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :feeds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
   before_action :login_required
    private
    def login_required
      redirect_to new_session_path unless current_user
    end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [ :show ,:edit ,:update ,:destroy ]

  # GET /feeds or /feeds.json
  def index
    @feeds = Feed.all
    @user=User.all
  end

  def favorites_list
    @favorites=Feed.where(fovorite_of_user_id: current_user.id)
  end


  # GET /feeds/1 or /feeds/1.json
  def show
    @feed = Feed.find(params[:id])
  end

  #define a favorite
 def make_it_as_my_favorite
    @feed=Feed.find params[:id]
    @feed.update(fovorite_of_user_id: current_user.id)
    redirect_to feeds_path
 end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit

  end

  # POST /feeds or /feeds.json
  def create
    @feed = Feed.new(feed_params)
    @feed.user_id=current_user.id
    respond_to do |format|
      if @feed.save
        PostMailMailer.with(user:current_user,feed:@feed).post_confirmation.deliver
        format.html { redirect_to @feed, notice: "We have sent to you an email.Please confirm the post !!" }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1 or /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1 or /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def confirm
    @feed = Feed.new(feed_params)
    render :new if @feed.invalid?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    private
    def feed_params
      params.require(:feed).permit(:image, :image_cache,:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
        @user = User.new
  end
def edit
  @user=User.find(current_user.id)
end

    # POST /feeds or /feeds.json
    def create
      @user= User.new(user_params)
      respond_to do |format|
        if @user.save
          MailsMailer.with(user: @user).welcome_email.deliver
          format.html { redirect_to @user, notice: "You have successfully regiter." }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
#-------------------------------------------
  def update
    @user=User.find(current_user.id)
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @feed= Feed.find_by user_id: @user.id
  end

  private
  def user_params
  params.require(:user).permit(:name,:email,:password,:password_confirmation,:image,:image_cache)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feed_helper.rb
module FeedHelper
        def choose_new_or_edit
            if action_name == 'new' || action_name == 'create'
              confirm_feeds_path
            elsif action_name == 'edit'
              feed_path
            end
          end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
    current_user.present?
    end
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true,url: choose_new_or_edit ) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="continer text-center">
    <div class="card text-center shadow d-flex">
      <div class="card-body w-100">
        <div class="field">
          <div class="form">
            <%= form.label :'Ajouter une image' ,class:'p-3 fs-3'%>
            <div class="form-group">
              <%= form.file_field :image,class:'btn btn-secondary' %>
               <%= form.hidden_field :image_cache %>
            </div>
            <%= form.label :'Ajouter un commentaire' ,class:'p-3 fs-3'%>
            <div class="form-group">
             
              <%= form.text_area :content,class:'p-3 fs-2 text-dark',autofocus:true %>
              <%= hidden_field_tag :user_id, value: @current_user.id %>
            </div>
          </div>
          
        </div>
        <div class="actions p-3">
          <%= form.submit%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1>Ecran de confirmation</h1>
<div class="container">
  <div class="text-center">
    <div class="column">
      <div class="row">
        <%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
        <%= image_tag(@feed.image.url,class:'img-fluid w-70 img-thumbnail') if @feed.image && @feed.image.url %>
        <p><%= @feed.content %></p>
        <%= form.hidden_field :content %>
        <%= form.hidden_field :image_cache %>
        <%= form.hidden_field :image%>
        <%= form.submit "Poster" ,class:'btn btn-success'%>
      <% end %>
          <%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
          <%= form.hidden_field :image_cache %>
          <%= form.submit "Revenir", name: "back" ,class:'btn btn-warning'%>
      <% end %>
      </div>
  </div>
</div>

app/views/feeds/edit.html.erb
<h1 class="p-3">Editing Post</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/favorites_list.html.erb
<div class="container">
  <% if @favorites.count > 0 %>
  <%=link_to 'Posts', feeds_path, class:'btn shadow'%>
<h1>Vos favories</h1>

<div class="row row-cols-1 row-cols-md-3">
  <% @favorites.each do |favorie| %>
  <div class="col m-3">
<div class="card" style="width:400px">
  <% if favorie.image.url %>
  <%= image_tag favorie.image.url,class:'card-img-top'%>
  <% else %>
  <%= image_tag("default.png",:alt => "--",class:'card-img-top' )%>
  <% end %>    
  <div class="card-body">
    <h4 class="card-title"><%=favorie.content%></h4>
    <hr>
    <%= link_to 'Show', favorie, class:'btn btn-success text-center'%>
    <% if favorie.user_id==current_user.id %>
    <%= link_to 'Edit', edit_feed_path(favorie.id), class:'btn btn-warning' %>
    <%= link_to 'Destroy', favorie, method: :delete, data: { confirm: 'Are you sure?' } , class:'btn btn-danger'%>
    <h3> Poster par vous</h3>
    <% else %>
    <h3> Poster par <%= User.find(favorie.user_id).name%></h3>
    <% end %>  
  </div>
</div>    
</div>
<%end%>
</div>
<%else%>
<h2>Vous n'avez pas encore de favories</h2>
<%end%>
<%= link_to 'Retour', feeds_path, class:'btn btn-primary'%>
</div>

app/views/feeds/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
<%=link_to 'Vos Favories', post_favorites_list_path, class:'btn shadow'%>
<h1>Posts</h1>
<div class="row row-cols-1 row-cols-md-3">
  <% @feeds.each do |feed| %>
  <div class="col m-3">
<div class="card" style="width:400px">
  <% if feed.image.url %>
  <%= image_tag feed.image.url,class:'card-img-top'%>
  <% else %>
  <%= image_tag("default.png",:alt => "--",class:'card-img-top' )%>
  <% end %>    
  <div class="card-body">
    <h4 class="card-title"><%=feed.content%></h4>
    <hr>
    <%= link_to 'Show', feed, class:'btn row btn-success text-center'%>
    
    <% if feed.user_id==current_user.id %>
  
    <%= link_to 'Edit', edit_feed_path(feed.id), class:'btn btn-warning m-3' %>
    <%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } , class:'btn btn-danger'%>
    <%=link_to 'like', post_favorite_path(feed.id), class:'btn btn-info'%>
    <h3> Poster par vous</h3>
    <% else %>
    <%=link_to 'like', post_favorite_path(feed.id), class:'btn btn-info'%>
    <h3> Poster par <%= User.find(feed.user_id).name%></h3>
    <% end %>  
  </div>
</div>    
</div>
<%end%>
</div>
</div>

app/views/feeds/new.html.erb
<h1 class="p-3">Create Post</h1>

<%= render 'form', feed: @feed %>

<h3 class="p-2"><%= link_to 'Back', feeds_path ,class:'btn btn-warning'%></h3>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container w-100">

<div class="text-center content d-block m-auto">
  <div class='text-center'style="width: 18rem;">
    <% if @feed.image.url %>

    <%= image_tag @feed.image.url,class:'img-fluid w-70 img-thumbnail'%>
    <% else %>
    <%= image_tag('default.png',:alt => "--",class:'img-fluid w-50 img-thumbnail')%>
    <% end %>
    <p><%= @feed.content %></p> 
<%= link_to 'Back', feeds_path %>
  </div>
 
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inst@Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <body class="">
      <nav class="navbar navbar-light bg-light shadow">
        <form class="container-fluid justify-content">
             <%= link_to "Home", feeds_path, class: "btn btn-outline-secondary me-2 m-3"%>
             <h1 class="text-center">Application de partage de photo</h1>
             <%= link_to "New Post", new_feed_path, class: "btn btn-outline-primary float-right m-3"%>
        </form>
      </nav>
      


    <div class="conatiner">
      <div class="card">
        <% flash.each do |key, value| %> 
        <%= content_tag(:div, value, class: "#{key}") %> 
        <% end %> 
        <% if logged_in? %> 
        <%= link_to "Profile", user_path(current_user.id),class:'btn btn-warning'%> 
        <%= link_to "Logout", session_path(current_user.id), method: :delete ,class:'btn btn-danger'%> 
        <% else %> 
        <%= link_to "Sign up", new_user_path ,class:'btn btn-primary'%> 
        <%= link_to "Login", new_session_path ,class:'btn btn-info' %> 
        <% end %> 
      </div>
      
    </div>
    <div class="py-3 mb-3">
      <div class="py-3 mb-3">
        <%= yield %>
      </div>
    </div>
    
   
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  <div class="card-footer text-center" style=" position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: black;
  color: white;
  text-align: center;">
    <footer class="Copyright"><p class="text-footer">Copirigth &copy All rigths reserved &middot</p></footer>
  </div>
</html>

app/views/users/edit.html.erb
<h1 class="p-2">Update Profil</h1> 
 <% if @user.errors.any? %> 
 <div id="error_explanation"> 
 <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2> 
 <ul> 
 <% @user.errors.full_messages.each do |message| %> 
 <li><%= message %></li> 
 <% end %> 
 </ul> 
 </div> 
 <% end %> 
 <%= form_with(model: @user, local: true,url: user_path) do |f| %> 
 
 <div class="container text-center">
    <div class="form">
        <div class="card justify-content bg-warning">
            <div class="d-flex flex-column">
                <%= f.label :name ,class:'text-light py-3 fs-3'%> 
                <div class="p-3"><%= f.text_field :name  ,class:'p-3'%> </div>

                <%= f.label :email ,class:'text-light py-3 fs-3'%> 
                <div class="p-3"><%= f.email_field :email  ,class:'p-3'%> </div>

                <%= f.label :password,class:'text-light py-3 fs-3' %> 
                <div class="p-3"><%= f.password_field :password ,class:'p-3'%> </div>

                <%= f.label :password_confirmation,class:'text-light py-3 fs-3' %> 
                <div class="p-3"><%= f.password_field :password_confirmation ,class:'p-3'%> </div>

             <div class="from-group">
                <%= f.label :image,class:'text-light py-3 fs-3' %> 
                <div class="p-3">
                    <%= f.file_field :image ,class:'p-3'%>
                    <%= f.hidden_field :image_cache %>
                </div>
             </div>      
           <div class="p-3"><%= f.submit "Valider",class:'btn btn-success btn-3d'%></div>
            </div>
        </div> 
    </div>
</div>
<% end %>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |f| %> 

<h1 class="p-2">Sign up</h1> 
 <% if @user.errors.any? %> 
    <div id="error_explanation"> 
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2> 
        <ul> 
            <% @user.errors.full_messages.each do |message| %> 
            <li><%= message %></li> 
            <% end %> 
        </ul> 
    </div> 
 <% end %> 
 <div class="container text-center">
    <div class="form">
        <div class="card justify-content bg-dark">
            <div class="d-flex flex-column">
                <%= f.label :name ,class:'text-light py-3 fs-3'%> 
                <div class="p-3"><%= f.text_field :name  ,class:'p-3'%> </div>

                <%= f.label :email ,class:'text-light py-3 fs-3'%> 
                <div class="p-3"><%= f.email_field :email  ,class:'p-3'%> </div>

                <%= f.label :password,class:'text-light py-3 fs-3' %> 
                <div class="p-3"><%= f.password_field :password ,class:'p-3'%> </div>

                <%= f.label :password_confirmation,class:'text-light py-3 fs-3' %> 
                <div class="p-3"><%= f.password_field :password_confirmation ,class:'p-3'%> </div>

                <div class="from-group">
                    <%= f.label :image,class:'text-light py-3 fs-3' %> 
                    <div class="p-3">
                        <%= f.file_field :image ,class:'p-3'%>
                        <%= f.hidden_field :image_cache %>
                    </div>
                </div>   
           <div class="actions p-3"><%= f.submit "Create my account",class:'btn btn-success btn-3d'%></div>
            </div>
        </div> 
    </div>
</div>
<% end %>

app/views/users/show.html.erb
<h1 class="p-3">Bienvenue <%= @user.name %> Sur Iclone</h1>
<style>
    .container{
    padding:5%;
}
.container .img{
    text-align:center;
}
.container .details{
    border-left:3px solid #ded4da;
}
.container .details p{
    font-size:15px;
    font-weight:bold;
}
</style>
<div class="card">
    <div class="container">
        <div class="row">
          <div class="col-md-6 img">
              <% if @user.image && @user.image.url%>
              <%= image_tag @user.image.url,class:'img text-center w-75 rounded-circle '%>
             
              <% else %>
              <%= image_tag('default.png',:alt => "--",class:'img-fluid w-50 img-thumbnail')%>
              <% end %>
          
          </div>
          <div class="col-md-6 details">
            <blockquote>
              <h5><%=@user.name%> </h5>
              <small><cite title="Source Title"> <%= @user.email%>  <i class="icon-map-marker"></i></cite></small>
            </blockquote>
            <%= link_to "Editer le profile", edit_user_path(@user.id) ,class:'btn btn-danger'%>
          </div>
        </div>
    </div>
    <div class="container text-center py-3">
        <%= link_to "Ajouter un post", new_feed_path,class:"btn btn-secondary text-center" %>
      <%= link_to "Voir les posts", feeds_path,class:"btn btn-secondary text-center" %>
      </div>
</div>